name: Main CI # action 명

on: # 이벤트 트리거
  push: # push event에 반응
    branches: # github repository의 branch가
      - main
      - develop

jobs: # jobs
  build: # GitHub-hosted runners env
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps: # steps
      - name: git clone #
        uses: actions/checkout@v3 #

      - name: AWS Credentials Production
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::597559577496:role/integration-shared-RoleForGitBuild
          aws-region: ap-northeast-2

      - name: npm install #
        run: npm run dependency #npm install

      - name: build #
        run: npm run build # code build

      - name: Deploy Production # 운영 배포
        if: github.ref == 'refs/heads/main'
        run: |
          aws sts get-caller-identity 
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            docs/dist s3://prd.inticons.com

      - name: CF Invalidation Production # 운영 배포
        if: github.ref == 'refs/heads/main'
        run: |
          aws sts get-caller-identity 
          aws cloudfront create-invalidation --distribution-id E2DYHQTJ062JGM --paths "/*"

      - name: Deploy Staging # 스테이징 배포
        if: github.ref == 'refs/heads/develop'
        run: |
          aws sts get-caller-identity 
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            docs/dist s3://stg.inticons.com

      - name: CF Invalidation Staging # 스테이징 배포
        if: github.ref == 'refs/heads/develop'
        run: |
          aws sts get-caller-identity
          aws cloudfront create-invalidation --distribution-id E5U62C7XQEO1I --paths "/*"

      - name: Deploy Dev # 개발 배포
        if: github.ref == 'refs/heads/develop'
        run: |
          aws sts get-caller-identity 
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            docs/dist s3://dev.inticons.com

      - name: CF Invalidation Deploy Dev # 개발 배포
        if: github.ref == 'refs/heads/develop'
        run: |
          aws sts get-caller-identity 
          aws cloudfront create-invalidation --distribution-id E27M30HZJ0NM49 --paths "/*"
